# Change baseurl before deploy
baseurl = "https://nicostern.de"
languageCode = "en-us"
paginate = 5
title = "Nico Stern"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

# TODO create acc
# Change it to your Disqus shortname before using
disqusShortname = "hugo-theme-stack"

[sitemap]
    changefreq = "weekly"
    priority = 0.5